### ISSUE TITLE
git clone with authentication 

### ISSUE THREAD

**Issue by Ultchad** [snipsco/hermes-protocol#86] opened 2019-04-07 14:29 UTC
I find in files:
- platforms/hermes-python/documentation/source/installation.rst
- platforms/hermes-python/README.rst

Instruction to clone reposititory:
`git clone git@github.com:snipsco/hermes-protocol.git`

It's clone authentication without it's that: 
`git clone https://github.com/snipsco/hermes-protocol.git`

Or I have make a mistake ?

**Comment by elbywan** [comment] 2019-04-07 19:29
Hey @Ultchad,

I'm sorry, but it's hard to understand what the issue is here. 
Could you please be more specific about the problem faced when cloning using ssh?

Also, there is a good article about ssh/https git in the [github docs](https://help.github.com/en/articles/which-remote-url-should-i-use).

**Comment by Ultchad** [comment] 2019-04-08 17:10
with this command:
`git clone git@github.com:snipsco/hermes-protocol.git`
I need login to github for clone the repository, but it's work

with:
`git clone https://github.com/snipsco/hermes-protocol.git` no login

But I do not know if it was a desire on your part.
If it's normally, sorry for this issue. it's can be close

**Comment by elbywan** [comment] 2019-04-08 20:05
@Ultchad Thanks for clarifying! 👍 

I don't have any strong feeling about that, @anthonyray WDYT?

**Comment by anthonyray** [comment] 2019-04-09 08:28
Hi @Ultchad , 

You have two possibilities to clone the `hermes-protocol` repository (as with every repository hosted on Github btw). 

- You can clone with `HTTPS`urls (`git clone https://github.com/snipsco/hermes-protocol.git`)
- You can clone using `SSH` (`git clone git@github.com:snipsco/hermes-protocol.git`)

To be able to clone with `SSH`, you first need to generate a SSH keypair, and add the generated public key to your Github account. When you do so, cloning will **not** prompt you for your login & password. 

When you use to clone using `HTTPS` you will be prompted for your login and password. 

In the documentation, I mention to use `SSH` to clone the repository, but you can choose any method. 

I'm closing for now, let us know if you run into any problem.

**Closed by anthonyray** 2019-04-09 08:28 UTC
Labels: question
